### ISSUE TITLE
Easting and northing checker misses Isle of Wight

### ISSUE THREAD

**Issue by colmjude** [digital-land/brownfield-land-collection#4]
Sites on the Isle of Wight are being classified as "out of range."

I think this is because of the [easting_northing_like](https://github.com/digital-land/brownfield-land-collection/blob/master/bin/harmonise.py#L114) check looking for numbers that are at least 6 digits long whereas sites from the Isle of Wight could just be 5 digits long (e.g. 455042,79849).

**Comment by psd** [comment]
We fixed this in https://github.com/digital-land/brownfield-land-collection/commit/dd41914e7e4b9249a0788b866630e01047f2f890
